### ISSUE TITLE
CMSIS RTOS API: Add a mechanism to wait for a thread to terminate

### ISSUE THREAD

**Issue by ilg-ul** [ARM-software/CMSIS#50]
The current specs do not define what happens if a thread exits, and there is no mechanism to tell is a thread has terminated or not.

According to POSIX, in [CMSIS++](http://micro-os-plus.github.io/cmsis-plus/) threads have a `join()` method, that can be used by other threads (usually the parent thread) to wait for thread termination.

Suggestion:
- add `join()`, to allow one thread to wait for another thread to terminate

**Comment by ombre5733** [comment]
If `join()` is added, I would also suggest to add `detach()` in order to be able to build a C++11 compatible `thread` class. I have implemented such a thing in [weos](https://github.com/ombre5733/weos/) (see also the [thread-source](https://github.com/ombre5733/weos/blob/master/src/_cmsis_rtos/_thread.hpp)) but would prefer if I did not have to make so many work-arounds.

**Comment by ReinhardKeil** [comment]
join attribute has been added to CMSIS-RTOS2

**Comment by ReinhardKeil** [comment]
completed
